### ISSUE TITLE
외부 접속시 로그인 안됨

### ISSUE THREAD

**Issue by fantayat** [netnamu/netnamu-issue#5]
로컬호스트 상태 이외에 네트워크를 통해 다른 PC에서 접속시 로그인이 안됩니다.
재현:
iPhone 이나 iPad로 서버에 접속을 시도한다.
/demo/n2-login
으로 로그인을 시도한다.
로그인이 되지 않음을 확인
윈도우PC 에서 크롬으로 접속시도시에도 동일

**Comment by fantayat** [comment]
로그인 안되는 증상
1. 로그인 페이지가 아예 나타나지 않는 경우
2. 로그인 페이지는 나타나지만 로그인 버튼을 클릭해도 아무런 진행이 없는 경우

**Comment by leihaht** [comment]
테스트 주소 알려주실수있나요? 저도 로그인 테스트 해보게요.

**Comment by fantayat** [comment]
그냥 내부 네트워크로 하면 됩니다. 별도이 외부 네트워크가 필요하지는 않구요. 서버 올리고 내부에서 아이폰이나 아이패드로 접속해보면 됩니다. 아니면 다른 PC를 이용해 내부 네트워크에 있는 서버에 접속해보시면 그 증상을 확인 할 수 있습니다.
서버와 물리적으로 분리된 다른 컴퓨터이면 재현해 볼 수 있습니다.

**Comment by leihaht** [comment]
request 주소를 받아서 그걸 api에 재사용으로 해결
