### ISSUE TITLE
모바일 브라우저 접속시 admin 메뉴 없어짐

### ISSUE THREAD

**Issue by fantayat** [netnamu/netnamu-issue#6]
IPad나 iPhone 에서 접속시 관리자 화면으로 들어가면 메뉴를 선택할 수 없습니다.
IPad의 경우 가로 모드에서는 메뉴가 나타나지만 세로 모드에서는 메뉴가 사라지고 햄버거 메뉴 아이콘을 눌러도 아무런 반응을 하지 않네요. 확인 바랍니다.

**Comment by leihaht** [comment]
반응형 기능이 현재 적용되있지않아서 그럴거예요. 1차 목표는 기본 기능을 구현하는것이라서, 반응형 UI는 뒤로 미뤄졌었네요.

**Comment by leihaht** [comment]
기능 구현함.
